SALES ARRAY
1)- ARRAY INFORNMATION

In [1]:
import numpy as np
sales=np.array([120,150,180,90,200,250,175,300,220,160])
print("Number of elements:",sales.size)
print("Dimensions:",sales.ndim)
print("type:",sales.dtype)
print("shape:",sales.shape)

Number of elements: 10
Dimensions: 1
type: int64
shape: (10,)

2)-TOTAL SALES

In [2]:
import numpy as np
sales=np.array([120,150,180,90,200,250,175,300,220,160])
total=np.sum(sales)
print("total sales:",total)

total sales: 1845

3)-AVERAGE SALES

In [3]:
import numpy as np
sales=np.array([120,150,180,90,200,250,175,300,220,160])
average = np.mean(sales)
print("average sales :",average)

average sales : 184.5

4)- MAXIMUM,MINIMUM,MAXIMUM_INDEX,MINIMUM_INDEX SALES

In [4]:
import numpy as np
sales=np.array([120,150,180,90,200,250,175,300,220,160])
maximum = np.max(sales)
print("maximum sales",sales)
minimum=np.min(sales)
print("minimum sales",sales)
maximum_index=np.argmax(sales)
print("index of maximum sales",maximum_index)
minimum_index=np.argmin(sales)
print("index of minimum sales",minimum_index)

maximum sales [120 150 180  90 200 250 175 300 220 160]
minimum sales [120 150 180  90 200 250 175 300 220 160]
index of maximum sales 7
index of minimum sales 3

5)- ACCESS ELEMENTS

In [5]:
import numpy as np
sales=np.array([120,150,180,90,200,250,175,300,220,160])
print("first element:",sales[0])
print("second element:",sales[1])
print("third element:",sales[2])
print("last element:",sales[-1])
print("second last element:",sales[-2])
print("third last element:",sales[-3])
print("index 2 to 6:",sales[2:7])

first element: 120
second element: 150
third element: 180
last element: 160
second last element: 220
third last element: 300
index 2 to 6: [180  90 200 250 175]

6)- REVERSE SALES ARRAY

In [6]:
import numpy as np
sales=np.array([120,150,180,90,200,250,175,300,220,160])
reverse = sales[::-1]
print("reverse:",reverse)

reverse: [160 220 300 175 250 200  90 180 150 120]

7)- SALES GREATER THAN 200

In [7]:
import numpy as np
sales=np.array([120,150,180,90,200,250,175,300,220,160])
result=sales[sales>200]
print("sales greater than 200",result)

sales greater than 200 [250 300 220]

8)- AGE BETWEEN 25 AND 35

In [8]:
import numpy as np
ages = np.array([22, 35, 28, 41, 19, 32, 25, 45, 30, 27])
result = ages[(ages >= 25) & (ages <= 35)]
print("Ages between 25 and 35:", result)

Ages between 25 and 35: [35 28 32 25 30 27]

9)- STUDENTS MARKS

In [9]:
import numpy as np
marks = np.array([
    [85, 78, 92],
    [67, 75, 80],
    [90, 88, 95],
    [55, 60, 65],
    [72, 85, 78]
])
print("First student's marks:", marks[0])
print("Second student's marks:", marks[1])
print("First subject marks:", marks[:, 0])
print("Second subject marks:", marks[:, 1])

First student's marks: [85 78 92]
Second student's marks: [67 75 80]
First subject marks: [85 67 90 55 72]
Second subject marks: [78 75 88 60 85]

10)- SUBJECT WISE AVERAGE

In [10]:
import numpy as np
marks = np.array([
    [85, 78, 92],
    [67, 75, 80],
    [90, 88, 95],
    [55, 60, 65],
    [72, 85, 78]
])
average = np.mean(marks, axis=0)
print("Subject-wise Average:", average)

Subject-wise Average: [73.8 77.2 82. ]

11)- INCREASE PRICES BY 10%

In [11]:
import numpy as np

prices = np.array([100, 250, 150, 500, 350, 120, 450, 200])

new_prices = prices + (prices * 10 / 100)

print("Original Prices:", prices)
print("Prices after 10% increase:", new_prices)

Original Prices: [100 250 150 500 350 120 450 200]
Prices after 10% increase: [110. 275. 165. 550. 385. 132. 495. 220.]

In [12]:
# 10th interview question (3rd most important question)
# loc and iloc---
# loc working with rows/label/name
# iloc working with index basic
# loc function mostly used in ml for convert categorical data into numerical.
# iloc function mostly used in ml for accessing or droping target variable


# QUESTION -> ML /AI/DL/LLM/GENERATIVE AI / WHICH CONCEPT ARE IMPORTANT
# DATA EXTRACTION -------MEANINGFUL INSIGHT----DATA ANYLYST
# DATA COLLECTION-----USED RIGHT ALGORITHM
# LOT ALGORITHM ------1 ROLE
# DATA KNOW                    WITHOUT DATA ALL PART ARE JUST LIKE FIELD OF STUDY

import pandas as pd
data ={
    "id": [101, 102, 103, 104],
    "name": ["Rahul", "Priya", "Amit", "Neha"],
    "post": ["Developer", "Manager", "Tester", "HR"],
    "salary": [35000, 60000, 42000, 38000],
    "city": ["Delhi", "Mumbai", "Pune", "Jaipur"],
    "age": [24, 32, 27, 29]
}
df = pd.DataFrame(data)
print(df)

    id   name       post  salary    city  age
0  101  Rahul  Developer   35000   Delhi   24
1  102  Priya    Manager   60000  Mumbai   32
2  103   Amit     Tester   42000    Pune   27
3  104   Neha         HR   38000  Jaipur   29

In [ ]:
print(df.loc[2])

id           103
name        Amit
post      Tester
salary     42000
city        Pune
age           27
Name: 2, dtype: object

In [ ]:
print(df.loc[2,"name"])

Amit

In [ ]:
print(df.loc[1:3])

    id   name     post  salary    city  age
1  102  Priya  Manager   60000  Mumbai   32
2  103   Amit   Tester   42000    Pune   27
3  104   Neha       HR   38000  Jaipur   29

In [ ]:
df.loc[df["salary"]>30000]

    id   name       post  salary    city  age
0  101  Rahul  Developer   35000   Delhi   24
1  102  Priya    Manager   60000  Mumbai   32
2  103   Amit     Tester   42000    Pune   27
3  104   Neha         HR   38000  Jaipur   29

In [ ]:
print(df.loc[[0,1,2]])

    id   name       post  salary    city  age
0  101  Rahul  Developer   35000   Delhi   24
1  102  Priya    Manager   60000  Mumbai   32
2  103   Amit     Tester   42000    Pune   27

In [ ]:
print(df.loc[:,["name","salary"]])

    name  salary
0  Rahul   35000
1  Priya   60000
2   Amit   42000
3   Neha   38000

In [ ]:
print(df.loc[df["age"]>25])

    id   name     post  salary    city  age
1  102  Priya  Manager   60000  Mumbai   32
2  103   Amit   Tester   42000    Pune   27
3  104   Neha       HR   38000  Jaipur   29

In [ ]:
df.iloc[0]

id              101
name          Rahul
post      Developer
salary        35000
city          Delhi
age              24
Name: 0, dtype: object

In [ ]:
print(df.iloc[2,3])

42000

In [ ]:
# get multiple records /rows using iloc function
df.iloc[0:len(df)]

    id   name       post  salary    city  age
0  101  Rahul  Developer   35000   Delhi   24
1  102  Priya    Manager   60000  Mumbai   32
2  103   Amit     Tester   42000    Pune   27
3  104   Neha         HR   38000  Jaipur   29

In [ ]:
# get first three record
print(df.iloc[0:3])

    id   name       post  salary    city  age
0  101  Rahul  Developer   35000   Delhi   24
1  102  Priya    Manager   60000  Mumbai   32
2  103   Amit     Tester   42000    Pune   27

In [ ]:
# get all data
print(df.iloc[:,-1])

0    24
1    32
2    27
3    29
Name: age, dtype: int64

In [ ]:
# get first 3 rows and 2 columns
print(df.iloc[0:3,0:2])

    id   name
0  101  Rahul
1  102  Priya
2  103   Amit

In [ ]:
# get last three record
print(df.iloc[-3:])

    id   name     post  salary    city  age
1  102  Priya  Manager   60000  Mumbai   32
2  103   Amit   Tester   42000    Pune   27
3  104   Neha       HR   38000  Jaipur   29

In [ ]:
df.iloc[1,2]

'Manager'

In [ ]:
df.loc[1,"post"]

'Manager'

In [ ]:
print(df.isnull().sum())

id        0
name      0
post      0
salary    0
city      0
age       0
dtype: int64

In [ ]:
print(df.count())

id        4
name      4
post      4
salary    4
city      4
age       4
dtype: int64

In [ ]:
df.fillna(0)

    id   name       post  salary    city  age
0  101  Rahul  Developer   35000   Delhi   24
1  102  Priya    Manager   60000  Mumbai   32
2  103   Amit     Tester   42000    Pune   27
3  104   Neha         HR   38000  Jaipur   29

In [ ]:
df.dropna()

    id   name       post  salary    city  age
0  101  Rahul  Developer   35000   Delhi   24
1  102  Priya    Manager   60000  Mumbai   32
2  103   Amit     Tester   42000    Pune   27
3  104   Neha         HR   38000  Jaipur   29

In [ ]:
import pandas as pd
df=pd.read_excel("Employee.xlsx")
df

    ID          Name                  Post  Salary       City  Age  Gender
0  101   Amit Sharma               Manager   65000      Delhi   35    Male
1  102    Neha Verma          HR Executive   42000     Mumbai   29  Female
2  103   Rahul Singh     Software Engineer   72000  Bengaluru   31    Male
3  104   Priya Gupta            Accountant   50000       Pune   28  Female
4  105   Karan Mehta       Sales Executive   39000     Jaipur   27    Male
5  106  Sneha Kapoor          Data Analyst   68000  Hyderabad   30  Female
6  107   Vikas Yadav           Team Leader   78000    Chennai   37    Male
7  108    Anjali Roy   Marketing Executive   47000    Kolkata   26  Female
8  109   Mohit Kumar  System Administrator   58000    Lucknow   33    Male
9  110  Pooja Mishra      Business Analyst   71000      Noida   32  Female

In [ ]:
len(df)

10

In [ ]:
df.head()

    ID         Name               Post  Salary       City  Age  Gender
0  101  Amit Sharma            Manager   65000      Delhi   35    Male
1  102   Neha Verma       HR Executive   42000     Mumbai   29  Female
2  103  Rahul Singh  Software Engineer   72000  Bengaluru   31    Male
3  104  Priya Gupta         Accountant   50000       Pune   28  Female
4  105  Karan Mehta    Sales Executive   39000     Jaipur   27    Male

In [ ]:
df.tail()

    ID          Name                  Post  Salary       City  Age  Gender
5  106  Sneha Kapoor          Data Analyst   68000  Hyderabad   30  Female
6  107   Vikas Yadav           Team Leader   78000    Chennai   37    Male
7  108    Anjali Roy   Marketing Executive   47000    Kolkata   26  Female
8  109   Mohit Kumar  System Administrator   58000    Lucknow   33    Male
9  110  Pooja Mishra      Business Analyst   71000      Noida   32  Female

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     int64
 1   Name    10 non-null     object
 2   Post    10 non-null     object
 3   Salary  10 non-null     int64
 4   City    10 non-null     object
 5   Age     10 non-null     int64
 6   Gender  10 non-null     object
dtypes: int64(3), object(4)
memory usage: 692.0+ bytes

In [ ]:
df.describe()

              ID        Salary        Age
count   10.00000     10.000000  10.000000
mean   105.50000  59000.000000  30.800000
std      3.02765  13767.917619   3.521363
min    101.00000  39000.000000  26.000000
25%    103.25000  47750.000000  28.250000
50%    105.50000  61500.000000  30.500000
75%    107.75000  70250.000000  32.750000
max    110.00000  78000.000000  37.000000

In [ ]:
df["Salary"].max()

78000

In [ ]:
df["Salary"].min()

39000

In [ ]:
df["Salary"].mean()

np.float64(59000.0)

In [ ]:
df["Salary"].sum()

np.int64(590000)

In [ ]:
df.isnull().sum()

ID        0
Name      0
Post      0
Salary    0
City      0
Age       0
Gender    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique()

ID        10
Name      10
Post      10
Salary    10
City      10
Age       10
Gender     2
dtype: int64

In [ ]:
df

    ID          Name                  Post  Salary       City  Age  Gender
0  101   Amit Sharma               Manager   65000      Delhi   35    Male
1  102    Neha Verma          HR Executive   42000     Mumbai   29  Female
2  103   Rahul Singh     Software Engineer   72000  Bengaluru   31    Male
3  104   Priya Gupta            Accountant   50000       Pune   28  Female
4  105   Karan Mehta       Sales Executive   39000     Jaipur   27    Male
5  106  Sneha Kapoor          Data Analyst   68000  Hyderabad   30  Female
6  107   Vikas Yadav           Team Leader   78000    Chennai   37    Male
7  108    Anjali Roy   Marketing Executive   47000    Kolkata   26  Female
8  109   Mohit Kumar  System Administrator   58000    Lucknow   33    Male
9  110  Pooja Mishra      Business Analyst   71000      Noida   32  Female

In [ ]:
df["Salary"].describe()

count       10.000000
mean     59000.000000
std      13767.917619
min      39000.000000
25%      47750.000000
50%      61500.000000
75%      70250.000000
max      78000.000000
Name: Salary, dtype: float64

In [ ]:
df["Salary"].fillna(df["Salary"].mean(), inplace=True)

/tmp/ipykernel_800/2346652894.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace=True)